### PR TITLE
github actions, fixes #15

### LINKED ISSUE #15: Binary wheels seem to be missing for py38 windows and mac
These would be nice to have, as python 3.9 is almost out.  If getting this to work with travis/appveyor is tough, the new github actions does windows/mac/linux and is pretty slick.

### PR DESCRIPTION
**Pull request by christopher-hesse**
Travis seems to be barely maintained at this point and their windows support has a few issues.  Github actions is a bit weird but at least it's popular and maintained and supports all the platforms with no additional setup.

### CODE REVIEW

**Comment by christopher-hesse** [comment]
Here's the link to the output on my fork: https://github.com/christopher-hesse/crc32c/actions/runs/148904345

**Comment by rtobar** [comment]
Neat, specially the fact that there's a single artifact zipfile containing all one would want. I'll have a closer look at the changes now, thanks a lot!

**Comment by rtobar** [comment]
Just tried two of the manylinux1 wheels (2.7-mu and 3.8) and both worked fine. I also tried the source distribution, and while it failed to compile it was only because of an issue that was uncovered by your work (not introduced by it), and by the fact that I've been building source distributions locally until now. The changes look great, so thanks again for keeping them so neat and well commented, it was a breeze to try out.

I'm now giving this a full try against test.pypi.org. After confirming all is working fine I'll merge this to the `master` branch, cleanup a bit (DOS line endings, adjust comments, update README badges, remove AppVeyor/Travis checks from GitHub, etc.), fix the source distribution generation, and produce a new 2.0.1 release.

**Comment by christopher-hesse** [comment]
I just copied and pasted the cibuildwheel example: https://github.com/joerick/cibuildwheel/blob/master/examples/github-deploy.yml

**Comment by rtobar** [comment]
Even easier! I might port in the future some other projects to use this, it looks quite neat.

**Pull request merged**
